Repository cloud-native-toolkit/terraform-azure-portworx, pull requests merged in 2022-06, with the labels that each got.

#17 Fixes issue processing portworx spec file
  .github/scripts/validate-deploy.sh
  README.md
  scripts/parse-portworx-config.sh
  scripts/portworx-prereq.sh
Labels: bug, patch

#18 First version release
  README.md
Labels: major

#21 Added ocp-login example to readme
  README.md
Labels: enhancement, patch
